name: flutter_bluetooth_serial
description: A custom fork of flutter_bluetooth_serial with namespace fixes
version: 1.0.0
homepage: https://github.com/edufolly/flutter_bluetooth_serial

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.github.edufolly.flutterbluetoothserial
        pluginClass: FlutterBluetoothSerialPlugin 